# Pandas

Where numpy is a mathematical library, the Pandas library is focused on working with and manipulating data. 

Let's read a data set from a csv-file.

In [2]:
import pandas as pd

titanic = pd.read_csv('Titanic.csv')
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

A common way of using Pandas is to select part of the data to use. Here we are selecting 4 columns by name. Generally, we use names to refer to columns and numbers to refer to rows.

In [3]:
titanic[['Pclass', 'Survived', 'Age', 'Sex']]

Pclass  Survived   Age     Sex
0         3         0  22.0    male
1         1         1  38.0  female
2         3         1  26.0  female
3         1         1  35.0  female
4         3         0  35.0    male
..      ...       ...   ...     ...
886       2         0  27.0    male
887       1         1  19.0  female
888       3         0   NaN  female
889       1         1  26.0    male
890       3         0  32.0    male

[891 rows x 4 columns]

One way to select data is to discard the data we don't want. Here we're dropping the first row (id = 0). We're using axis=0 to tell Pandas we're dropping a row, not a column.

In [4]:
titanic.drop(0, axis=0)

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
5        0            330877   8.4583   NaN        Q  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[890 rows x 12 columns]

This is dropping the 'Survived' column. Note that axis=1 here.

In [5]:
X = titanic.drop('Survived', axis=1)

In [6]:
titanic[['Pclass', 'Survived', 'Age', 'Sex']].dropna()


Pclass  Survived   Age     Sex
0         3         0  22.0    male
1         1         1  38.0  female
2         3         1  26.0  female
3         1         1  35.0  female
4         3         0  35.0    male
..      ...       ...   ...     ...
885       3         0  39.0  female
886       2         0  27.0    male
887       1         1  19.0  female
889       1         1  26.0    male
890       3         0  32.0    male

[714 rows x 4 columns]

In [7]:
titanic[titanic.Age > 30]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
6              7         0       1   
11            12         1       1   
..           ...       ...     ...   
873          874         0       3   
879          880         1       1   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
3        0    113803  53.1000  C123        S  
4        0    373450   8.0500   NaN        S  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
..     ...       ...      ...   ...      ...  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
881      0    349257   7.8958   NaN        S  
885      5    382652  29.1250   NaN        Q  
890      0    370376   7.7500   NaN        Q  

[305 rows x 12 columns]

In [8]:
titanic[(titanic.Age > 30) & (titanic.Survived == 1)]


PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
11            12         1       1   
15            16         1       2   
21            22         1       2   
..           ...       ...     ...   
857          858         1       1   
862          863         1       1   
865          866         1       2   
871          872         1       1   
879          880         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
..                                                 ...     ...   ...    ...   
857                             Daly, Mr. Peter Denis     male  51.0      0   
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
3        0    113803  53.1000  C123        S  
11       0    113783  26.5500  C103        S  
15       0    248706  16.0000   NaN        S  
21       0    248698  13.0000   D56        S  
..     ...       ...      ...   ...      ...  
857      0    113055  26.5500   E17        S  
862      0     17466  25.9292   D17        S  
865      0    236852  13.0000   NaN        S  
871      1     11751  52.5542   D35        S  
879      1     11767  83.1583   C50        C  

[124 rows x 12 columns]

It's important to realize that none of these methods change the data set. They create a new data set and returns it. In order to store the result, we have to store it in a variable.

Below is a realistic example:
1. Drop all the rows that has missing data. Note, that we need to reassign to `titanic` so actually save the result.
2. We extract all the numeric data because that's what we need for the machine learning algorithms.
3. We still want to keep the information about sex, so we use one-hot encoding for it.


In [9]:
numeric_titanic = titanic[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch']]
numeric_titanic = numeric_titanic.dropna()

one_hot_sex = pd.get_dummies(titanic['Sex'], dtype='int')

numeric_titanic = pd.concat([numeric_titanic, one_hot_sex], axis='columns')
numeric_titanic

Survived  Pclass   Age  SibSp  Parch  female  male
0         0.0     3.0  22.0    1.0    0.0       0     1
1         1.0     1.0  38.0    1.0    0.0       1     0
2         1.0     3.0  26.0    0.0    0.0       1     0
3         1.0     1.0  35.0    1.0    0.0       1     0
4         0.0     3.0  35.0    0.0    0.0       0     1
..        ...     ...   ...    ...    ...     ...   ...
859       NaN     NaN   NaN    NaN    NaN       0     1
863       NaN     NaN   NaN    NaN    NaN       1     0
868       NaN     NaN   NaN    NaN    NaN       0     1
878       NaN     NaN   NaN    NaN    NaN       0     1
888       NaN     NaN   NaN    NaN    NaN       1     0

[891 rows x 7 columns]

So, obviously having both female and male columns is redundant. We generally don't want that, so let's drop one of them.

In [10]:
numeric_titanic = numeric_titanic.drop('male', axis=1)
numeric_titanic

Survived  Pclass   Age  SibSp  Parch  female
0         0.0     3.0  22.0    1.0    0.0       0
1         1.0     1.0  38.0    1.0    0.0       1
2         1.0     3.0  26.0    0.0    0.0       1
3         1.0     1.0  35.0    1.0    0.0       1
4         0.0     3.0  35.0    0.0    0.0       0
..        ...     ...   ...    ...    ...     ...
859       NaN     NaN   NaN    NaN    NaN       0
863       NaN     NaN   NaN    NaN    NaN       1
868       NaN     NaN   NaN    NaN    NaN       0
878       NaN     NaN   NaN    NaN    NaN       0
888       NaN     NaN   NaN    NaN    NaN       1

[891 rows x 6 columns]

One thing, we can use Pandas for is computing descriptive statistical features.

In [11]:
print(numeric_titanic.mean())
print()
print(numeric_titanic.median())
print()
print(numeric_titanic.mode())
print()
print(numeric_titanic.var())
print()
print(numeric_titanic.std())


Survived     0.406162
Pclass       2.236695
Age         29.699118
SibSp        0.512605
Parch        0.431373
female       0.352413
dtype: float64

Survived     0.0
Pclass       2.0
Age         28.0
SibSp        0.0
Parch        0.0
female       0.0
dtype: float64

   Survived  Pclass   Age  SibSp  Parch  female
0       0.0     3.0  24.0    0.0    0.0       0

Survived      0.241533
Pclass        0.702663
Age         211.019125
SibSp         0.864497
Parch         0.728103
female        0.228475
dtype: float64

Survived     0.491460
Pclass       0.838250
Age         14.526497
SibSp        0.929783
Parch        0.853289
female       0.477990
dtype: float64


You can use the `describe` function to get many statistical features at once.

In [12]:
print(numeric_titanic.describe())

         Survived      Pclass         Age       SibSp       Parch      female
count  714.000000  714.000000  714.000000  714.000000  714.000000  891.000000
mean     0.406162    2.236695   29.699118    0.512605    0.431373    0.352413
std      0.491460    0.838250   14.526497    0.929783    0.853289    0.477990
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.125000    0.000000    0.000000    0.000000
50%      0.000000    2.000000   28.000000    0.000000    0.000000    0.000000
75%      1.000000    3.000000   38.000000    1.000000    1.000000    1.000000
max      1.000000    3.000000   80.000000    5.000000    6.000000    1.000000


Sometimes we want to use the data as a matrix to use in computations. We can easily turn it into a numpy matrix using the `to_numpy` function.

In [13]:
print(numeric_titanic.to_numpy())

[[ 0.  3. 22.  1.  0.  0.]
 [ 1.  1. 38.  1.  0.  1.]
 [ 1.  3. 26.  0.  0.  1.]
 ...
 [nan nan nan nan nan  0.]
 [nan nan nan nan nan  0.]
 [nan nan nan nan nan  1.]]
