In [4]:
import numpy as np

def sigmoid(t):
  return 1/(1 + np.exp(-t))

def heaviside(t):
  return np.round(sigmoid(t))

# Turns an input vector (x0, x1) into (x0, x1, 1) to allow for a bias term
def biased(v):
  return np.append([1], v)

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])


In [7]:
def nn(x):
    l1 = np.array([
        [-1.5, 1, 1],
        [-.5, 1, 1]
    ])
    l2 = np.array([
        [-.5, -1, 1]
    ])
    input = l1 @ biased(x)
    hidden = heaviside(input)
    o = l2 @ biased(hidden)
    return heaviside(o)

print([nn(x) for x in X])

[array([0.]), array([1.]), array([1.]), array([0.])]


In [13]:
def nn(x):
    l1 = np.array([
        [-1.5, 1, 1],
        [-.5, 1, 1]
    ])
    l2 = np.array([
        [-.5, -1, 1]
    ])
    input = l1 @ biased(x)
    hidden = sigmoid(input)
    o = l2 @ biased(hidden)
    return sigmoid(o)

p = [nn(x) for x in X]
yhat = np.round(p)
print(yhat)

def loss(y, p):
    return - (y * np.log(p) + (1-y) * np.log(1-p))

losses = [loss(y[i], p[i]) for i in range(X.shape[0])]

L = np.mean(losses)
print(L)

[[0.]
 [0.]
 [0.]
 [0.]]
0.6905392895752118


In [14]:
def nn(x):
    l1 = np.array([
        [-4, 8, 8],
        [12, -8, -8]
    ])
    l2 = np.array([
        [-1, .75, .75]
    ])
    input = l1 @ biased(x)
    hidden = sigmoid(input)
    o = l2 @ biased(hidden)
    return heaviside(o)

print([nn(x) for x in X])

[array([0.]), array([1.]), array([1.]), array([0.])]


In [17]:
def nn(x):
    l1 = np.array([
        [-4, 8, 8],
        [12, -8, -8]
    ])
    l2 = np.array([
        [-1, .75, .75]
    ])
    input = l1 @ biased(x)
    hidden = sigmoid(input)
    o = l2 @ biased(hidden)
    return sigmoid(o)

print([nn(x) for x in X])

p = [nn(x) for x in X]
yhat = np.round(p)
print(yhat)

losses = [loss(y[i], p[i]) for i in range(X.shape[0])]

L = np.mean(losses)
print(L)

[array([0.44114536]), array([0.61609846]), array([0.61609846]), array([0.44114536])]
[[0.]
 [1.]
 [1.]
 [0.]]
0.5331071848579314


In [19]:
def nn(x):
    l1 = np.array([
        [-4, 8, 8],
        [12, -8, -8]
    ])
    l2 = np.array([
        [-10, 7.5, 7.5]
    ]) 
    input = l1 @ biased(x)
    hidden = sigmoid(input)
    o = l2 @ biased(hidden)
    return sigmoid(o)

print([nn(x) for x in X])

p = [nn(x) for x in X]
yhat = np.round(p)
print(yhat)

losses = [loss(y[i], p[i]) for i in range(X.shape[0])]

L = np.mean(losses)
print(L)

[array([0.08586912]), array([0.99125255]), array([0.99125255]), array([0.08586912])]
[[0.]
 [1.]
 [1.]
 [0.]]
0.04928372827156684
