In [7]:
import numpy as np

M = np.array([
    [2, 1], 
    [1, -.5]
    ])

M_inv = np.linalg.inv(M)
print(M_inv)
print(M @ M_inv)

[[ 0.25  0.5 ]
 [ 0.5  -1.  ]]
[[1. 0.]
 [0. 1.]]


In [8]:
M1 = np.array([
    [2, 1], 
    [1, .5]
    ])
M1_inv = np.linalg.inv(M1)


LinAlgError: Singular matrix

In [12]:
y = np.array([
    9, 
    -.5
    ])
x = M_inv @ y
print(x)

[2. 5.]


In [10]:
print(M.shape)
print(y.shape)

(2, 2)
(2,)


In [17]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

energy = pd.read_csv('temp_energy.csv')
X = energy.drop(['Energy consumption/kWh'], axis=1)
y = energy['Energy consumption/kWh']
energy.to_numpy()

array([[-10. ,  46.5],
       [ -5. ,  37.9],
       [  0. ,  33.2],
       [  5. ,  27.5],
       [ 10. ,  20.3],
       [ 15. ,  21.1],
       [ 20. ,  14.2],
       [ 25. ,   6.3],
       [ 30. ,   5.6]])

In [18]:

poly = PolynomialFeatures(degree = 1)
X1 = poly.fit_transform(X)

print(X1)

[[  1. -10.]
 [  1.  -5.]
 [  1.   0.]
 [  1.   5.]
 [  1.  10.]
 [  1.  15.]
 [  1.  20.]
 [  1.  25.]
 [  1.  30.]]


In [ ]:
XT = X1.T // Transpose
print(XT)

XTX = XT @ X1
print(XTX)

XTX1 = np.linalg.inv(XTX)

print(XTX1)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [-10.  -5.   0.   5.  10.  15.  20.  25.  30.]]
[[   9.   90.]
 [  90. 2400.]]
[[ 0.17777778 -0.00666667]
 [-0.00666667  0.00066667]]
